variable "azure_os_type" { default="Linux"}
variable "azure_source_image_publisher" { default="Canonical"}
variable "azure_source_image_offer" { default="UbuntuServer"}
variable "azure_source_image_sku" { default="18.04-LTS-gen2"}
variable "aws_role_arn" { default=null}
variable "aws_session_name" { default=null}
variable "aws_external_id" { default=null}
variable "docker_image" { default=null}
variable "docker_export_path" { default=null}
variable "azure_subscription_id" { default=""}
variable "azure_client_id" { default=""}
variable "azure_client_secret" { default=""}
variable "azure_tenant_id" { default=""}
variable "azure_async_resourcegroup_delete" { default=true}
variable "azure_managed_image_name" { default=""}
variable "azure_managed_image_resource_group_name" { default=""}
variable "azure_build_resource_group_name" { default=""}
variable "azure_virtual_network_resource_group_name" { default=""}
variable "azure_virtual_network_name" { default=""}
variable "azure_virtual_network_subnet_name" { default=""}
variable "azure_private_virtual_network_with_public_ip" { default=true}
variable "azure_allowed_inbound_ip_addresses" { default=null}
variable "azure_vm_size" { default="StandardDS3v4"}
variable "azure_sig_source_subscription" { default=""}
variable "azure_sig_source_resource_group" { default=""}
variable "azure_sig_source_gallery_name" { default=""}
variable "azure_sig_source_image_name" { default=""}
variable "azure_sig_source_image_version" { default=""}
variable "azure_sig_destination_subscription" { default=""}
variable "azure_sig_destination_redestination_group" { default=""}
variable "azure_sig_destination_gallery_name" { default=""}
variable "azure_sig_destination_image_name" { default=""}
variable "azure_sig_destination_image_version" { default=""}
variable "azure_sig_destination_replication_regions" { default=""}
variable "azure_sig_destination_storage_account_type" { default=""}
variable "build_network" { default ="false" }
variable "build_resource_group" { default = "" }
variable "azure_target" { default = "managed_image"}
variable "azure_source" { default = "shared_image_gallery" }
variable "azure_auth" { default = "sp" }